#############################################################################
# Makefile for building: Dextrous
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Apr 5 17:29:42 2012
# Project:  Dextrous.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile Dextrous.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtWebKit -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtWebKit -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dextrous.cpp \
		facebooklogin.cpp \
		facebookwindow.cpp \
		login.cpp \
		main.cpp \
		marketcart.cpp \
		musicsearchwindow.cpp \
		newsviewer.cpp \
		tweetviewer.cpp moc_dextrous.cpp \
		moc_facebooklogin.cpp \
		moc_facebookwindow.cpp \
		moc_login.cpp \
		moc_marketcart.cpp \
		moc_musicsearchwindow.cpp \
		moc_newsviewer.cpp \
		moc_tweetViewer.cpp \
		qrc_images.cpp
OBJECTS       = dextrous.o \
		facebooklogin.o \
		facebookwindow.o \
		login.o \
		main.o \
		marketcart.o \
		musicsearchwindow.o \
		newsviewer.o \
		tweetviewer.o \
		moc_dextrous.o \
		moc_facebooklogin.o \
		moc_facebookwindow.o \
		moc_login.o \
		moc_marketcart.o \
		moc_musicsearchwindow.o \
		moc_newsviewer.o \
		moc_tweetViewer.o \
		qrc_images.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		Dextrous.pro
QMAKE_TARGET  = Dextrous
DESTDIR       = 
TARGET        = Dextrous

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dextrous.h ui_facebooklogin.h ui_facebookwindow.h ui_login.h ui_marketcart.h ui_musicsearchwindow.h ui_newsviewer.h ui_twitter.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Dextrous.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtWebKit.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile Dextrous.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtWebKit.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Dextrous.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Dextrous1.0.0 || $(MKDIR) .tmp/Dextrous1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Dextrous1.0.0/ && $(COPY_FILE) --parents dextrous.h facebooklogin.h facebookwindow.h login.h marketcart.h musicsearchwindow.h newsviewer.h tweetViewer.h .tmp/Dextrous1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/Dextrous1.0.0/ && $(COPY_FILE) --parents dextrous.cpp facebooklogin.cpp facebookwindow.cpp login.cpp main.cpp marketcart.cpp musicsearchwindow.cpp newsviewer.cpp tweetviewer.cpp .tmp/Dextrous1.0.0/ && $(COPY_FILE) --parents dextrous.ui facebooklogin.ui facebookwindow.ui login.ui marketcart.ui musicsearchwindow.ui newsviewer.ui twitter.ui .tmp/Dextrous1.0.0/ && (cd `dirname .tmp/Dextrous1.0.0` && $(TAR) Dextrous1.0.0.tar Dextrous1.0.0 && $(COMPRESS) Dextrous1.0.0.tar) && $(MOVE) `dirname .tmp/Dextrous1.0.0`/Dextrous1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Dextrous1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dextrous.cpp moc_facebooklogin.cpp moc_facebookwindow.cpp moc_login.cpp moc_marketcart.cpp moc_musicsearchwindow.cpp moc_newsviewer.cpp moc_tweetViewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dextrous.cpp moc_facebooklogin.cpp moc_facebookwindow.cpp moc_login.cpp moc_marketcart.cpp moc_musicsearchwindow.cpp moc_newsviewer.cpp moc_tweetViewer.cpp
moc_dextrous.cpp: ui_dextrous.h \
		dextrous.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) dextrous.h -o moc_dextrous.cpp

moc_facebooklogin.cpp: ui_facebooklogin.h \
		facebooklogin.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) facebooklogin.h -o moc_facebooklogin.cpp

moc_facebookwindow.cpp: ui_facebookwindow.h \
		facebookwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) facebookwindow.h -o moc_facebookwindow.cpp

moc_login.cpp: ui_login.h \
		login.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_marketcart.cpp: ui_marketcart.h \
		marketcart.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) marketcart.h -o moc_marketcart.cpp

moc_musicsearchwindow.cpp: ui_musicsearchwindow.h \
		musicsearchwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) musicsearchwindow.h -o moc_musicsearchwindow.cpp

moc_newsviewer.cpp: ui_newsviewer.h \
		newsviewer.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) newsviewer.h -o moc_newsviewer.cpp

moc_tweetViewer.cpp: ui_twitter.h \
		tweetViewer.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) tweetViewer.h -o moc_tweetViewer.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/hs.png \
		images/amazon.jpg \
		images/fk.png
	/usr/lib64/qt4/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dextrous.h ui_facebooklogin.h ui_facebookwindow.h ui_login.h ui_marketcart.h ui_musicsearchwindow.h ui_newsviewer.h ui_twitter.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dextrous.h ui_facebooklogin.h ui_facebookwindow.h ui_login.h ui_marketcart.h ui_musicsearchwindow.h ui_newsviewer.h ui_twitter.h
ui_dextrous.h: dextrous.ui
	/usr/lib64/qt4/bin/uic dextrous.ui -o ui_dextrous.h

ui_facebooklogin.h: facebooklogin.ui
	/usr/lib64/qt4/bin/uic facebooklogin.ui -o ui_facebooklogin.h

ui_facebookwindow.h: facebookwindow.ui
	/usr/lib64/qt4/bin/uic facebookwindow.ui -o ui_facebookwindow.h

ui_login.h: login.ui
	/usr/lib64/qt4/bin/uic login.ui -o ui_login.h

ui_marketcart.h: marketcart.ui
	/usr/lib64/qt4/bin/uic marketcart.ui -o ui_marketcart.h

ui_musicsearchwindow.h: musicsearchwindow.ui
	/usr/lib64/qt4/bin/uic musicsearchwindow.ui -o ui_musicsearchwindow.h

ui_newsviewer.h: newsviewer.ui
	/usr/lib64/qt4/bin/uic newsviewer.ui -o ui_newsviewer.h

ui_twitter.h: twitter.ui
	/usr/lib64/qt4/bin/uic twitter.ui -o ui_twitter.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

dextrous.o: dextrous.cpp dextrous.h \
		ui_dextrous.h \
		marketcart.h \
		ui_marketcart.h \
		login.h \
		ui_login.h \
		tweetViewer.h \
		ui_twitter.h \
		musicsearchwindow.h \
		ui_musicsearchwindow.h \
		newsviewer.h \
		ui_newsviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dextrous.o dextrous.cpp

facebooklogin.o: facebooklogin.cpp facebooklogin.h \
		ui_facebooklogin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facebooklogin.o facebooklogin.cpp

facebookwindow.o: facebookwindow.cpp facebookwindow.h \
		ui_facebookwindow.h \
		dextrous.h \
		ui_dextrous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facebookwindow.o facebookwindow.cpp

login.o: login.cpp login.h \
		ui_login.h \
		dextrous.h \
		ui_dextrous.h \
		facebookwindow.h \
		ui_facebookwindow.h \
		facebooklogin.h \
		ui_facebooklogin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

main.o: main.cpp dextrous.h \
		ui_dextrous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

marketcart.o: marketcart.cpp dextrous.h \
		ui_dextrous.h \
		marketcart.h \
		ui_marketcart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o marketcart.o marketcart.cpp

musicsearchwindow.o: musicsearchwindow.cpp dextrous.h \
		ui_dextrous.h \
		musicsearchwindow.h \
		ui_musicsearchwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o musicsearchwindow.o musicsearchwindow.cpp

newsviewer.o: newsviewer.cpp newsviewer.h \
		ui_newsviewer.h \
		dextrous.h \
		ui_dextrous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newsviewer.o newsviewer.cpp

tweetviewer.o: tweetviewer.cpp tweetViewer.h \
		ui_twitter.h \
		dextrous.h \
		ui_dextrous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tweetviewer.o tweetviewer.cpp

moc_dextrous.o: moc_dextrous.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dextrous.o moc_dextrous.cpp

moc_facebooklogin.o: moc_facebooklogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facebooklogin.o moc_facebooklogin.cpp

moc_facebookwindow.o: moc_facebookwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facebookwindow.o moc_facebookwindow.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_marketcart.o: moc_marketcart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_marketcart.o moc_marketcart.cpp

moc_musicsearchwindow.o: moc_musicsearchwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_musicsearchwindow.o moc_musicsearchwindow.cpp

moc_newsviewer.o: moc_newsviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newsviewer.o moc_newsviewer.cpp

moc_tweetViewer.o: moc_tweetViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tweetViewer.o moc_tweetViewer.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

